[package]
name = "dedoc"
version = "0.1.1"
description = "Terminal-based viewer for DevDocs documentation"
authors = ["toiletbril"]
readme = "README.md"

edition = "2021"
rust-version = "1.66"

license = "GPLv3"
keywords = ["docs", "cli"]

[profile.release]
opt-level = 3
strip = true
lto = true

[dependencies]
toiletcli = { version = "0.9.3", features = ["colors", "flags"] }
html2text = { version = "0.6.0", features = ["ansi_colours"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.106"
attohttpc = { version = "0.26.1", features = ["tls-native"] }
flate2 = { version = "1.0.27", features = ["default", "rust_backend"] }
tar = "0.4.40"
