[package]
name = "dedoc"
version = "0.2.0"
description = "Terminal-based viewer for DevDocs documentation"
authors = ["toiletbril"]
readme = "README.md"

edition = "2021"
rust-version = "1.66"

license = "GPLv3"
keywords = ["docs", "cli"]

[profile.release]
opt-level = 3
strip = true
lto = true

[dependencies]
toiletcli = { version = "0.9.4", features = ["colors", "flags"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.106"
attohttpc = { version = "0.26.1", features = ["tls-native"] }
html2md = "0.2.14"
termimad = "0.25.2"
